### PR TITLE
WIP: Add Turkish bad words

### PR DESCRIPTION
**Pull request by ghost**
Initial bad-words list for Turkish. It needs to be refined.

### CODE REVIEW

**Comment by hughsie** [comment]
Can you add it to the big existing file please?

**Comment by ghost** [comment]
Sorry, I forgot to add Work in Progress tag. I will add in a few days.

**Comment by ghost** [comment]
I am unable to continue the project for the following reasons:
- Turkish is an agglutinative language and capturing only the body is not enough.
- Even when we start from the root, some words do not have the same meaning even though their root looks the same.
- Currently, I have listed more than  one thousand words and it contains many more badwords than any all listed languages, also and it portrays Turkish as a bad language.

**Comment by hughsie** [comment]
> also and it portrays Turkish as a bad language

I really don't think that's true. I think adding even some works (like the f... y...) ones would be super useful even if we can't capture everything.

**Pull request closed without merging**
